version: '3.8'
services:
  web:
    ports:
      - 80:80
    restart: unless-stopped
    build: 
      context: ./frontend
      dockerfile: ./frontend/Dockerfile.prod
    image: vidly_web:1
      
  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      - DB_URL=mongodb://db/vidly
    command: ./docker-entrypoint.sh
    restart: unless-stopped
    image: vidly_api:1

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - vidly:/data/db
    

volumes:
  vidly:


